config/routes.rb
Rails.application.routes.draw do
  #devise facebook login
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get '/favicon.bmp' => redirect(path: "/assets/favicon.ico", host: Wasgeht::Application.config.application_url)
  get '/apple-touch-icon-*png' => redirect(path: '/assets/apple-touch-icon.png', host: Wasgeht::Application.config.application_url)

  root  :to => "city_select#index"

  get '/robots.txt'  => 'robots#index', defaults: { format: :text }

  #devise facebook logout
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy', as: :sign_out
  end

  scope '/:area' do
    get '/' => "events#index", :as => :events
    get '/' => "events#index", :as => :area
    get 'e/:uuid' => "events#show", constraints: { uuid: /[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12}/ }, :as => :event
    get 'a/:uuid' => "events#show", constraints: { uuid: /[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12}/ },   defaults: { format: :amp }, :as => :event_amp
    get 'i/:uuid' => "events#show", constraints: { uuid: /[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12}/ },   defaults: { format: :ics }, :as => :event_ics
    get '/was-geht-demnaechst-ab' => "future_events#index", :as => :future_events
    get '/d/was-geht-am-:date-ab' => "future_events#show", :as => :future_event, constraints: { date: /\d(\d)?\.\d(\d)?\.\d\d\d\d/ }
    get '/ueber-uns'    => 'legal#about', :as => :about
    get '/impressum'    => 'legal#imprint', :as => :imprint
    get '/datenschutz'  => 'legal#privacy', :as => :privacy
    get '/agb'          => 'legal#tos', :as => :tos

    scope module: 'sitemap' do
      get '/sitemap.xml'    => 'city#index',  defaults: { format: :xml }, as: :sitemap_city_index
      get '/sitemap/root.xml'    => 'city#root',   defaults: { format: :xml }, as: :sitemap_city_root
      get '/sitemap/:page.xml'    => 'city#show',   defaults: { format: :xml }, constraints: { :page => /\d*+/ }, as: :sitemap_city_show
    end

    scope '/kontakt' do
      get  '/' => 'legal#imprint', :as => :contact_index
    end

    scope '/flyer-hochladen' do
      get  '/' => "upload#index", :as => :upload_index
      post '/' => "upload#create"
      post '/e' => "upload#create_event", as: :upload_index_event
      get  '/finish' => "upload#finish", :as => :finish_upload_index
    end
  end

  get '*unmatched_route', to: 'application#route_not_found'
end

app/views/partials/_empty_state.erb
<div class="offset"></div>
<div class="light-wrapper page-title">
  <div class="container inner">
    <h1><%= empty_state_title %></h1>
  </div>
</div>
<div class="dark-wrapper">
  <div class="container inner">
    <div class="row">
      <div id="upload" class="col-sm-6">
        <h3>Deine Party bei wgha.de hochladen</h3>
          <p>Erstelle zuerst deine Veranstaltung auf Facebook. Gib hier anschließend den Link zum Facebook Event ein.
          z.B.: <%= link_to 'https://www.facebook.com/events/285261306205168', 'https://www.facebook.com/events/285261306205168' %>.</p>

          <p>Wir holen den Event von Facebook.</p>
          
          <% unless current_user %>
            <%= link_to '<img src="/fb_button/fb_login_button.png" style="max-width: 250px; max-height: 60px;" />'.html_safe, user_facebook_omniauth_authorize_path, :class => "", :"data-width" => 600, :"data-height" => 400 %>
          <% else %>

            <% if @event %>
            <a href="<%= event_url(uuid: @event.uuid) %>">
              <div class="alert alert-success">
                <strong>Der Event ist hier hochgeladen:</strong>
                <p><%= link_to event_url(uuid: @event.uuid, area: @event.area), event_url(uuid: @event.uuid, area: @event.area) %></p>
              </div>
            </a>
            <% elsif @token && @token.errors.any? %>
              <div class="row">
                <div class="span8 offset3">
                  <!-- Start Alerts -->
                  <div class="alert alert-warning">
                    <strong>Bitte überprüfe die folgenden Felder:</strong>
                    <ul>
                      <% @token.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                      <% end %>
                      <% if @candidate %>
                      <p><%= link_to event_url(uuid: @candidate.uuid, area: @candidate.area), event_url(uuid: @candidate.uuid, area: @candidate.area) %></p>
                      <% end %>
                    </ul>
                  </div>
                  <!-- End Alerts -->
                </div>
              </div>
            <% end %>
          
            <div class="form-container">
              <form action="<%= upload_index_event_url %>" method="post" class="form-horizontal" accept-charset="UTF-8" novalidate>
                <div class="control-group">
                  <label class="control-label">Facebook Event Link:</label>
                  <div class="controls">
                    <input name="utf8" type="hidden" value="&#x2713;" />
                    <input name="token[token]" class="span6" type="text" value="<%= "https://www.facebook.com/events/" + @token.token unless @token.nil? || @token.token.blank? %>">
                  </div>
                </div>
                <div class="control-group">
                  <div class="controls">
                    <button name="commit" type="submit" class="btn rounded">Party hochladen</button>
                  </div>
                </div>
              </form>
            </div>
          <% end %>
        <!-- /.form-container -->
      </div>
    </div>
  </div>
  <!-- /.container -->
</div>
<div class="dark-wrapper">
  <div class="container inner">
    <% unless current_user %>
      <div class="row">
        <div id="upload" class="col-sm-6">
          <h3>Deine Party bei wgha.de hochladen</h3>
            <p>Erstelle zuerst deine Veranstaltung auf Facebook. Gib hier anschließend den Link zum Facebook Event ein.
            z.B.: <%= link_to 'https://www.facebook.com/events/285261306205168', 'https://www.facebook.com/events/285261306205168' %>.</p>

            <p>Wir holen den Event von Facebook.</p>

            <% if @event %>
            <a href="<%= event_url(uuid: @event.uuid) %>">
              <div class="alert alert-success">
                <strong>Der Event ist hier hochgeladen:</strong>
                <p><%= link_to event_url(uuid: @event.uuid, area: @event.area), event_url(uuid: @event.uuid, area: @event.area) %></p>
              </div>
            </a>
            <% elsif @token && @token.errors.any? %>
              <div class="row">
                <div class="span8 offset3">
                  <!-- Start Alerts -->
                  <div class="alert alert-warning">
                    <strong>Bitte überprüfe die folgenden Felder:</strong>
                    <ul>
                      <% @token.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                      <% end %>
                      <% if @candidate %>
                      <p><%= link_to event_url(uuid: @candidate.uuid, area: @candidate.area), event_url(uuid: @candidate.uuid, area: @candidate.area) %></p>
                      <% end %>
                    </ul>
                  </div>
                  <!-- End Alerts -->
                </div>
              </div>
            <% end %>
            <div class="form-container">
              <form action="<%= upload_index_url %>" method="post" class="form-horizontal" accept-charset="UTF-8" novalidate>
                <div class="control-group">
                  <label class="control-label">Facebook Event Link:</label>
                  <div class="controls">
                    <input name="utf8" type="hidden" value="&#x2713;" />
                    <input name="token[token]" class="span6" type="text" value="<%= "https://www.facebook.com/events/" + @token.token unless @token.nil? || @token.token.blank? %>">
                  </div>
                </div>
                <div class="control-group">
                  <div class="controls">
                    <button name="commit" type="submit" class="btn rounded">Party hochladen</button>
                  </div>
                </div>
              </form>
            </div>
          <!-- /.form-container -->
        </div>
      </div>
    <% else %>
      <%= link_to '<img src="/fb_button/fb_logout_button.png" style="max-width: 350px; max-height: 100px; margin-left: -50px;" />'.html_safe, sign_out_url, :method => :delete %>
    <% end %>
  </div>
  <!-- /.container -->
</div>
<!-- /.dark-wrapper -->
<script type="text/javascript">
  $(document).ready(function(){
    $("a.popup").click(function(e) {
      popupCenter($(this).attr("href"), $(this).attr("data-width"), $(this).attr("data-height"), "authPopup");
      e.stopPropagation(); return false;
    });
    if(window.opener) {
      window.close()
      window.opener.location.reload(true);
    }
  });

  function popupCenter(url, width, height, name) {
    var left = (screen.width/2)-(width/2);
    var top = (screen.height/2)-(height/2);
    return window.open(url, name, "menubar=no,toolbar=no,status=no,width="+width+",height="+height+",toolbar=no,left="+left+",top="+top);
  }

</script>

app/views/partials/_events_display.erb
<% if @events.blank? %>

<%= render "partials/empty_state", :empty_state_title => "Noch ist nichts für #{@current_area.name} eingetragen. Schaue einfach später nochmals vorbei!" %>

<% else %>

<div class="offset"></div>

<div class="light-wrapper page-title">
  <div class="container inner">
    <h1><strong><%= display_title %></strong></h1>
    <div class="collapse navbar-collapse pull-right">
    </div>
  </div>
</div>
<div class="dark-wrapper">
  <div class="container inner">
    <div class="portfolio">
      <ul class="items col4">
        <% for event in @events %>
        <% next if event.photo.nil? %>
        <li class="item video">
          <a href="<%= event_url(uuid: event.uuid) %>">
            <figure class="icon-overlay medium icn-more"><%= image_tag(event.photo.external_cache_thumb_path, :size => '333x222' , :alt => t(:alt_text_for_image, :event_name => h(event.name), :location_name => h(event.location), :area => @current_area.name)) %></figure>
            <div class="image-caption">
              <h3><%= event.name %></h3>
              <span class="meta"><%= event.start_time.strftime("%H:%M") %>Uhr@<%= event.location %></span>
            </div>
          </a>
        </li>
        <!-- /.item -->
        <script type="application/ld+json">
        {
          "@context" : "http://schema.org",
          "@type" : "Event",
          "name" : "<%= event.name %>",
          "startDate" : "<%= event.start_time.utc.iso8601 %>",
          "endDate" : "<%= (event.start_time + 4.hours).utc.iso8601 %>",
          "performer": {
            "@type": "PerformingGroup",
            "name": "<%= event.name %>"
            },
          "offers": {
            "@type": "Offer",
            "availability": "http://schema.org/InStock",
            "price": "0",
            "priceCurrency": "EUR",
            "url": "<%= event_url( area: event.area, uuid: event.uuid) %>",
            "validFrom": "<%= event.start_time.utc.iso8601 %>"
            },
          "location" : {
            "@type" : "Place",
            "name" : "<%= event.location %>",
            "address" : {
              "@type" : "PostalAddress",
              "addressCountry":"DE",
              "streetAddress" : "<%= event.street %>",
              "addressLocality" : "<%= event.city %>",
              "postalCode" : "<%= event.zipcode %>"
            }
          },
          "image" : "<%= event.photo.url %>",
          "description" : "<%= event.description.gsub("\n", " ") if event.description %>",
          "url" : "<%= event_url( area: event.area, uuid: event.uuid) %>"
        }
        </script>
        <% end %>
      </ul>
    </div>
    <!-- /.portfolio -->
  </div>
  <!-- /.container -->
</div>
<!-- /.dark-wrapper -->
<% end %>