config/routes.rb
Rails.application.routes.draw do
  #devise facebook login
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get '/favicon.bmp' => redirect(path: "/assets/favicon.ico", host: Wasgeht::Application.config.application_url)
  get '/apple-touch-icon-*png' => redirect(path: '/assets/apple-touch-icon.png', host: Wasgeht::Application.config.application_url)

  root  :to => "city_select#index"

  get '/robots.txt'  => 'robots#index', defaults: { format: :text }

  #devise facebook logout
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy', as: :sign_out
  end

  scope '/:area' do
    get '/' => "events#index", :as => :events
    get '/' => "events#index", :as => :area
    get 'e/:uuid' => "events#show", constraints: { uuid: /[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12}/ }, :as => :event
    get 'a/:uuid' => "events#show", constraints: { uuid: /[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12}/ },   defaults: { format: :amp }, :as => :event_amp
    get 'i/:uuid' => "events#show", constraints: { uuid: /[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12}/ },   defaults: { format: :ics }, :as => :event_ics
    get '/was-geht-demnaechst-ab' => "future_events#index", :as => :future_events
    get '/d/was-geht-am-:date-ab' => "future_events#show", :as => :future_event, constraints: { date: /\d(\d)?\.\d(\d)?\.\d\d\d\d/ }
    get '/ueber-uns'    => 'legal#about', :as => :about
    get '/impressum'    => 'legal#imprint', :as => :imprint
    get '/datenschutz'  => 'legal#privacy', :as => :privacy
    get '/agb'          => 'legal#tos', :as => :tos

    scope module: 'sitemap' do
      get '/sitemap.xml'    => 'city#index',  defaults: { format: :xml }, as: :sitemap_city_index
      get '/sitemap/root.xml'    => 'city#root',   defaults: { format: :xml }, as: :sitemap_city_root
      get '/sitemap/:page.xml'    => 'city#show',   defaults: { format: :xml }, constraints: { :page => /\d*+/ }, as: :sitemap_city_show
    end

    scope '/kontakt' do
      get  '/' => 'legal#imprint', :as => :contact_index
    end

    scope '/flyer-hochladen' do
      get  '/' => "upload#index", :as => :upload_index
      post '/' => "upload#create"
      post '/e' => "upload#create_event", as: :upload_index_event
      get  '/finish' => "upload#finish", :as => :finish_upload_index
    end
  end

  get '*unmatched_route', to: 'application#route_not_found'
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                  :integer          not null, primary key
#  photo_id            :integer
#  uuid                :binary(64)
#  eid                 :string(255)
#  name                :string(255)
#  location            :string(255)
#  street              :string(255)
#  zipcode             :string(255)
#  city                :string(255)
#  area                :string(255)
#  country             :string(255)
#  website             :string(255)
#  start_time          :datetime
#  email_from_uploader :string(255)
#  description         :text(65535)
#  description_html    :text(65535)
#  ticket_url          :string(255)
#  facebook_image_url  :string(255)
#  status              :string(255)
#  updated_at          :datetime         not null
#  created_at          :datetime         not null
#  description_amp     :text(65535)
#

class Event < ApplicationRecord
  include AutoHtml

  belongs_to :photo, :dependent => :destroy

  validates_presence_of :name, :location, :city, :country, :facebook_image_url
  validates_length_of   :name, :maximum => 500, :allow_blank => true
  validates :city, inclusion: { in: City.pluck(:name)}
  validates_uniqueness_of :eid, :case_sensitive => false, :allow_blank =>true
  validates_uniqueness_of :uuid, :case_sensitive => false, :allow_blank =>true

  scope :backwards,          -> { order('"index_events_on_start_time" desc') }
  scope :forwards,           -> { order('"index_events_on_start_time" asc') }
  scope :random,             -> { order("RAND()") }
  scope :includes_photos,    -> { includes(:photo) }
  scope :in_area,            ->(area) { where(area: area.domain) }
  scope :upcoming,           -> { where('start_time > ?', (Time.zone.now - 8.hours).end_of_day + 8.hours) }
  scope :starting_from_today,-> { where('start_time > ?', (Time.zone.now - 8.hours).beginning_of_day + 8.hours) }
  scope :past,               -> { where('start_time < ?', (Time.zone.now - 8.hours).beginning_of_day + 8.hours) }
  scope :on_same_day_as,     ->(event) { where(start_time: ((event.start_time - 8.hours).beginning_of_day + 8.hours)..((event.start_time - 8.hours).end_of_day + 8.hours)) }
  scope :on_day,             ->(time) { where(start_time: ((time - 8.hours).beginning_of_day + 8.hours)..((time - 8.hours).end_of_day + 8.hours)) }
  scope :in_the_next_month,  -> {where(start_time: (((Time.zone.now + 1.days) - 8.hours).beginning_of_day + 8.hours)..(((Time.zone.now - 8.hours) ).end_of_day + 8.hours + 1.months - 2.days))}
  scope :today,              -> { where(start_time: ((Time.zone.now - 8.hours).beginning_of_day + 8.hours)..((Time.zone.now - 8.hours).end_of_day + 8.hours)) }

  before_save :trigger_auto_html

  def to_param
    "#{uuid}"
  end

  def website=(url)
    begin
      url = Addressable::URI.heuristic_parse(url)
    rescue
      self[:website] = ""
      errors.add(:base, "Webseite hat kein gültiges Format.")
    end
    self[:website] = url.to_s
  end

  def to_ical(event_url)
    calendar = Icalendar::Calendar.new
    calendar.prodid = 'www.wasgehtheuteab.de'
    event = Icalendar::Event.new
    event.dtstart = self.start_time.strftime("%Y%m%dT%H%M%S")
    event.dtend = (self.start_time + 3.hours).strftime("%Y%m%dT%H%M%S")
    event.summary = self.name
    event.description = "Partys & Konzerte - Ausgehen im Nachtleben von #{self.city}. Wir zeigen dir auf www.wasgehtheuteab.de wohin man abends ausgehen kann."
    event.location = "#{self.location}, #{self.street}, #{self.zipcode} #{self.city}"
    event.ip_class = "PUBLIC"
    event.created = self.created_at
    event.last_modified = self.updated_at
    event.uid = self.uuid
    event.url = event_url
    calendar.add_event(event)
    calendar.to_ical
  end

  private
  def trigger_auto_html
    begin
      self[:description_html] = auto_html(self[:description]) do
        # html_escape this should be also set but makes problems with umlauts
        sanitize
        youtube(width: 320, height: 200)
        vimeo(width: 320, height: 200)
        link(short_link_name: true, rel: "nofollow")
        redcarpet
      end
      self[:description_amp] = auto_html(self[:description]) do
        # html_escape this should be also set but makes problems with umlauts
        sanitize
        amp_youtube(width: 320, height: 200)
        amp_vimeo(width: 320, height: 200)
        link(short_link_name: true, rel: "nofollow")
        redcarpet
      end
    rescue
      self[:description_amp] = self[:description_html] = auto_html(self[:description]) do
        # html_escape this should be also set but makes problems with umlauts
        sanitize
        redcarpet
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  force_ssl if Rails.env.production?
  before_action :cache_control

  def index
    if stale?(etag: Event.in_area(@current_area).today.pluck(:updated_at), public: true)
      @time = Time.zone.now - 8.hours
      @events = Event.backwards.includes_photos.in_area(@current_area).today
      respond_to do |format|
        format.html
        format.rss { render :layout => false }
      end
    end
  end

  def show
    if stale?(etag: Event.where(uuid: params[:uuid]).pluck(:updated_at).first, last_modified: Event.where(uuid: params[:uuid]).pluck(:updated_at).first, public: true)
      @event = Event.includes_photos.where(uuid: params[:uuid]).first

      if !@event || @event.photo.nil?
        if !@current_area
          return redirect_to root_url(area: nil), status: 301
        end

        return render template: "error_handling/not_found", status: 404, formats: 'html'
      end

      @events_preview = Event.includes_photos.where(id: Event.where.not(id: @event.id).in_area(@current_area).on_same_day_as(@event).pluck(:id).sample(6))

      respond_to do |format|
        format.html
        format.amp { render :layout => false }
        format.ics { render plain: @event.to_ical(event_url(uuid: @event.uuid)) }
      end
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def soundcloud(text)
    begin
      links = []
      text.gsub(/(https?:\/\/)?(www.)?soundcloud\.com\/\S*/) do |match|
        new_uri = match.to_s
        clean_url = new_uri.match(/(?i)\b((?:[a-z][\w-]+:(?:\/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}\/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?«»“”‘’]))/)
        new_uri = (clean_url[0] =~ /^https?\:\/\/.*/) ? URI(clean_url[0]) : URI("https://#{clean_url[0]}")
        new_uri.normalize!
        links << "<iframe width='100%' height='166' scrolling='no' frameborder='no' src='https://w.soundcloud.com/player/?url=#{new_uri}'></iframe>"
      end
      return links.join(' ')
    rescue
    end
  end
end

app/views/events/index.html.erb
<% content_for :title do %>
<%= t(:whats_up_in, :scope => 'helpers.events', :area => @current_area.name, :date => I18n.localize(@time, :format => :title)) %> - <%= I18n.localize(@time, :format => :index) %>
<% end %>

<% content_for :description do %>
Partys &amp; Konzerte am <%= I18n.localize(@time, :format => :index) %> - Ausgehen im Nachtleben von <%= @current_area.name %>. Wir zeigen dir auf www.wgha.de wohin man abends ausgehen kann.
<% end %>

<% content_for :facebook_property do %>
<meta content="website" property="og:type"/>
<meta content='<%= t(:whats_up_in, :scope => 'helpers.events', :area => @current_area.name, :date => I18n.localize(@time, :format => :title)) %>' property='og:title'>
<meta content='was geht heute ab' property='og:site_name'>
<meta content='<%= events_url %>' property='og:url'>
<meta content='Wir zeigen dir auf www.wgha.de wohin man abends ausgehen kann.' property='og:description'>
<meta content='<%= image_url 'wgha.de.png' %>' property='og:image'>
<meta property="og:image:type" content="image/png">
<% end %>

<% content_for :hreflang do %>
<link rel="alternate" href="<%= events_url %>" hreflang="de-de" />
<% end %>

<%= render "partials/events_display", :display_title => "Was geht heute am #{I18n.localize(@time, :format => :index)} in #{@current_area.name}?" %>

<script type="application/ld+json">
  {
    "@context":"http://schema.org",
    "@type":"BreadcrumbList",
    "itemListElement":[
    {"item":{"@id":"<%= root_url(area: nil) %>","name":"<%= "Alle Städte" %> "},"@type":"ListItem","position":1},
    {"item":{"@id":"<%= events_url(area: @current_area.domain) %>","name":"<%= @current_area.name %>"},"@type":"ListItem","position":2}]}
</script>

app/views/events/show.amp.erb
<!doctype html>
<html amp lang="de">
<head>
  <meta charset="utf-8">
  <title><%= t(:whats_up_show, :scope => 'helpers.events', :area => @current_area.name, :city => @event.city, :date => I18n.localize(@event.start_time, :format => :title), :event => @event.name, :location => @event.location) %></title>
  <link rel="canonical" href="<%= event_url( area: @event.area, uuid: @event.uuid) %>" />
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "NewsArticle",
    "mainEntityOfPage":{
      "@type":"WebPage",
      "@id":"<%= event_amp_url( area: @event.area, uuid: @event.uuid) %>"
    },
    "headline": "<%= @event.name %>",
    "image": {
      "@type": "ImageObject",
      "url": "<%= @event.photo.url %>",
      "height": <%= @event.photo.height %>,
      "width": <%= @event.photo.width %>
    },
    "datePublished": "<%= @event.created_at.utc.iso8601 %>",
    "dateModified": "<%= @event.updated_at.utc.iso8601 %>",
    "author": {
      "@type": "Person",
      "name": "wgha"
    },
    "publisher": {
      "@type": "Organization",
      "name": "Was geht heute ab?",
      "logo": {
        "@type": "ImageObject",
        "url": "<%= image_url 'logo.png' %>",
        "width": 55,
        "height": 40
      }
    },
    "description": "<%= t(:meta_description_event, :area => @current_area.name, :event_name => @event.name, :date => @event.start_time.strftime("%d.%m.%Y"), :location => @event.location, :tags => nil, :scope => 'helpers.events', extension: 'de') %>"
  }
  </script>
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <style amp-custom>
  @font-face {
    font-family: 'Raleway';
    font-style: normal;
    font-weight: 400;
    src: local('Raleway'), url(https://fonts.gstatic.com/s/raleway/v9/cIFypx4yrWPDz3zOxk7hIQLUuEpTyoUstqEm5AMlJo4.woff) format('woff');
  }
  @font-face {
    font-family: 'Raleway';
    font-style: normal;
    font-weight: 700;
    src: local('Raleway Bold'), local('Raleway-Bold'), url(https://fonts.gstatic.com/s/raleway/v9/JbtMzqLaYbbbCL9X6EvaI73hpw3pgy2gAi-Ip7WPMi0.woff) format('woff');
  }
  /* any custom style goes here; and remember, body margin can not be declared */
  body {
    background-color: white;
    font-family: 'Raleway',sans-serif;
    font-size: 14px;
    font-weight: 500;
    color: #7a7a7a;
  }

  h1, h2, h3, h4, h5, h6 {
    font-family: 'Raleway',sans-serif;
    margin-top: 0;
    color: #616161;
    margin-bottom: 10px;
    font-weight: 800;
  }

  h1 {
    font-size: 26px;
    line-height: 30px;
  }

  a { text-decoration: none; }
  amp-img { max-width: 100%; }

  .container {
    max-width: 1170px;
    margin: 0 auto;
  }
  .row {
    margin-left: -15px;
    margin-right: -15px;
  }

  .row:before, .row:after {
    content: " ";
    display: table;
  }

  .clear { clear: both; }

  .main-header {
    background: #333c45;
    padding: 30px 0;
  }

  .logo { float: left; }
  .main-menu {
    float: left;
  }

  .main-menu ul li {
    display: inline-block;
    margin: 0 15px;
  }

  .main-menu ul li a {
    color: #FFF;
    text-transform: uppercase;
    font-weight: bold;
    text-decoration: none;
    font-size: 13px;
  }

  .header-ad, .footer-ad {
    text-align: center;
    margin: 25px;
    max-width: 100%;
    overflow: hidden;
  }

  #city-name {
    display: none;
    color: #FFF;
    font-size: 18px;
    float: right;
    margin-top: 8px;
  }

  .main {
    background: #f9f9f9;
    padding: 70px 0;
    border-top: 1px solid #e3e3e3;
    border-bottom: 1px solid #e3e3e3;
  }

  .sidebar, .content {
    float: left;
    padding: 0 15px;
  }

  .sidebar { width: 25%; }
  .content { width: 66.66%; }

  .sidebar hr {
    border: 0;
    border-top: 1px solid #ddd;
    margin: 15px 0;
  }

  ul.details {
    list-style-type: none;
    padding: 0;
  }

  ul.details li {
    font-weight: bold;
    margin: 5px 0;
    color: #555;
  }

  .sidebar a {
    font-style: italic;
    text-decoration: none;
    color: #3f8dbf;
  }

  .main-footer {
    background: #2c2c2c;
    color: #cacaca;
    padding: 30px 0;
  }

  .main-footer a {
    color: #cacaca;
    font-weight: 500;
  }

  .footer-left { float: left; }
  .footer-right { float: right; }
  .footer-menu a { margin: 5px; }

  #city-name {
    display: block;
  }

  @media( max-width: 1200px ) {
    .container { margin: 0 20px; }
  }

  @media( max-width: 768px ) {
    .content, .sidebar {
      width: 80%;
      margin: 0 auto;
      padding: 20px 10%;
    }

    .main-menu { display: none; }
    .footer-menu { display: none; }

    .footer-left {
      float: none;
      text-align: center;
    }
  }
  </style>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async 
      custom-element="amp-auto-ads"
      src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
   </script>
</head>
<body>
  <amp-auto-ads type="adsense" data-ad-client="ca-pub-2540422383235659"></amp-auto-ads>
  <header class="main-header">
    <div class="container">

      <div class="logo">
        <a href="<%= area_url %>" target="_blank"><amp-img src="<%= image_url 'logo.png' %>" width="55" height="40"></amp-img></a>
      </div>

      <div id="city-name">
        WGHA? <%= @current_area.name %>
      </div>

      <div class="clear"></div>
    </div>
  </header>

  <article class="main">
    <div class="container">

      <div class="row">
        <aside class="sidebar">
          <h1><%= @event.name %></h1>
          <time><%= I18n.localize(@event.start_time, :format => :event) %></time>

          <hr>

          <ul class="details">
            <li><%= @event.location %></li>
            <li><%= @event.street %></li>
            <li><%= @event.zipcode %> <%= @event.city %></li>
          </ul>

          <hr>

          <strong>
            <%= google_maps_amp_link(@event, 'Google Maps') %> | <%= link_to 'Webseite', @event.website, rel: "nofollow" %> | <%= link_to 'Permalink', event_amp_url( area: @event.area, uuid: @event.uuid) %> | <%= link_to 'Kalender', event_ics_path( area: @event.area, uuid: @event.uuid) %>
          </strong>
          <hr>
        </aside>

        <section class="content">
          <amp-img src="<%= @event.photo.external_cache_path %>" width="<%= @event.photo.width %>" height="<%= @event.photo.height %>" layout="responsive"></amp-img>
          <div>
            <%= raw @event.description_amp %>
          </div>
        </section>

        <div class="clear"></div>
      </div>
    </div>
  </article>
<footer class="main-footer">
  <div class="container">

    <div class="footer-left">
      <a href="<%= root_url(area: nil) %>" target="_blank">© <%= Time.zone.now.year %> www.wasgehtheuteab.de</a>
    </div>

    <div class="clear"></div>
  </div>
</footer>
</body>
</html>

app/views/events/show.html.erb
<% content_for :title do %>
<%= t(:whats_up_show, :scope => 'helpers.events', :area => @current_area.name, :city => @event.city, :date => I18n.localize(@event.start_time, :format => :title), :event => @event.name, :location => @event.location) %>
<% end %>

<% content_for :description do %>
<%= t(:meta_description_event, :area => @current_area.name, :event_name => @event.name, :date => @event.start_time.strftime("%d.%m.%Y"), :location => @event.location, :tags => nil, :scope => 'helpers.events', extension: 'de') %>
<% end %>

<% content_for :facebook_property do %>
<meta content="website" property="og:type"/>
<meta content='<%= @event.name %>' property='og:title'/>
<meta content='was geht heute ab' property='og:site_name'/>
<meta content='<%= event_url( area: @event.area, uuid: @event.uuid) %>' property='og:url'/>
<meta content='<%= t(:meta_description_event, :area => @current_area.name, :event_name => @event.name, :date => @event.start_time.strftime("%d.%m.%Y"), :location => @event.location, :tags => nil, :scope => 'helpers.events', extension: 'de') %>' property='og:description'/>
<meta content='<%= @event.photo.url %>' property='og:image'/>
<meta property="og:image:type" content="image/jpeg"/>
<meta property="og:updated_time" content="<%= @event.updated_at.iso8601 %>"/>
<meta property="og:type" content="events.event"/>
<meta property="og:locale" content="de_DE">
<% end %>

<% content_for :hreflang do %>
<link rel="alternate" href="<%= event_url(area: @event.area, uuid: @event.uuid) %>" hreflang="de-de" />
<link rel="alternate" type="text/calendar" title="Calendar" href="<%= event_ics_path( area: @event.area, uuid: @event.uuid) %>" />
<link rel="amphtml" href="<%= event_amp_url(area: @event.area, uuid: @event.uuid) %>" />
<link rel="canonical" href="<%= event_url(area: @event.area, uuid: @event.uuid) %>" />
<meta name="keywords" content="Was geht heute ab, <%= @event.name %>, <%= @event.name %> party, <%= @event.name %> <%= @event.city %>, <%= @event.name %> <%= @event.city %> party"/>



<% end %>

<div class="offset">
</div>
<div class="dark-wrapper">
  <div class="container inner">

    <div class="row">
      <div class="col-sm-3">
        <ul class="item-details">
          <li><h1><%= @event.name %></h1></li>
        </ul>
        <ul class="item-details">
          <li><%= I18n.localize(@event.start_time, :format => :event) %></li>
          <li>
            <span>
              <%= @event.location %>
            </span><br/>
            <span>
              <span>
                <%= @event.street %>
              </span>
              <br/>
              <span>
                <%= @event.zipcode %>
              </span>
              <span>
                <%= @event.city %>
              </span>
            </span>
          </li>
        </ul>
        <ul class="item-details">
          <li></li>
          <li><%= google_maps_link(@event, 'Auf Google Maps anzeigen') %></li>
          <li><%= link_to 'Zum Kalender hinzufügen', event_ics_path( area: @event.area, uuid: @event.uuid) %></li>
          <li><%= link_to 'Permanenter Link zu diesem Event', event_path( area: @event.area, uuid: @event.uuid) %></li>
          <li><%= link_to 'Event auf Facebook anzeigen', @event.website, rel: "nofollow", target: '_blank' %></li>
        </ul>
        <ul class="item-details">
          <li></li>
          <li></li>
        </ul>
      </div>
      <!-- /.col-sm-4 -->
      <div class="col-sm-8">
        <div class="owl-slider-wrapper">
          <div class="item">
            <%= image_tag(@event.photo.external_cache_path, alt: t(:alt_text_for_image, event_name: @event.name, location_name: @event.location, area: @current_area.name)) %>
          </div>

          <div>
            <%= raw @event.description_html %>
          </div>
        </div>
        <%= raw soundcloud(@event.description) %>

      </div>
      <!-- /.col-sm-8 -->

    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
</div><!-- /.dark-wrapper -->

<div class="dark-wrapper">
  <div class="container inner">
    <div class="section-title text-center">
      <h2>Was geht noch?</h2>
      <span class="icon"><i class="icon-picture"></i></span>
    </div>
    <div class="owl-portfolio owlcarousel carousel-th">
      <% for event in @events_preview %>
      <% next if !event.photo %>
      <div class="item">
        <a href="<%= event_url(uuid: event.uuid) %>">
          <figure class="icon-overlay medium icn-link"><%= image_tag(event.photo.external_cache_thumb_path, :size => '333x222' , :alt => t(:alt_text_for_image, :event_name => h(event.name), :location_name => h(event.location), :area => @current_area.name)) %>
          </figure>
          <div class="image-caption">
            <h3><%= event.name %></h3>
            <span class="meta"><%= event.start_time.strftime("%H:%M") %>Uhr@<%= event.location %></span>
          </div>
        </a>
      </div>
      <!-- /.item -->
      <% end %>

    </div>
    <!-- /.owlcarousel -->
  </div>
</div>
<script type="application/ld+json">
  {
    "@context":"http://schema.org",
    "@type":"BreadcrumbList",
    "itemListElement":[
    {"item":{"@id":"<%= root_url(area: nil) %>","name":"<%= "Alle Städte" %> "},"@type":"ListItem","position":1},
    {"item":{"@id":"<%= events_url(area: @current_area.domain) %>","name":"<%= @current_area.name %>"},"@type":"ListItem","position":2},
    {"item":{"@id":"<%= event_url(area: @current_area.domain, uuid: @event.uuid) %>","name":"<%= @event.name %>"},"@type":"ListItem","position":3}]}
  </script>
  <script type="application/ld+json">
    {
      "@context" : "http://schema.org",
      "@type" : "Event",
      "name" : "<%= @event.name %>",
      "startDate" : "<%= @event.start_time.utc.iso8601 %>",
      "endDate" : "<%= (@event.start_time + 4.hours).utc.iso8601 %>",
      "performer": {
        "@type": "PerformingGroup",
        "name": "<%= @event.name %>"
      },
      "offers": {
        "@type": "Offer",
        "availability": "http://schema.org/InStock",
        "price": "0",
        "priceCurrency": "EUR",
        "url": "<%= event_url( area: @event.area, uuid: @event.uuid) %>",
        "validFrom": "<%= @event.start_time.utc.iso8601 %>"
      },
      "location" : {
        "@type" : "Place",
        "name" : "<%= @event.location %>",
        "address" : {
          "@type" : "PostalAddress",
          "addressCountry":"DE",
          "streetAddress" : "<%= @event.street %>",
          "addressLocality" : "<%= @event.city %>",
          "postalCode" : "<%= @event.zipcode %>"
        }
      },
      "image" : "<%= @event.photo.url %>",
      "description" : "<%= @event.description.gsub("\n", " ") if @event.description %>",
      "url" : "<%= event_url( area: @event.area, uuid: @event.uuid) %>"
    }
  </script>