config/routes.rb
Rails.application.routes.draw do
  #devise facebook login
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get '/favicon.bmp' => redirect(path: "/assets/favicon.ico", host: Wasgeht::Application.config.application_url)
  get '/apple-touch-icon-*png' => redirect(path: '/assets/apple-touch-icon.png', host: Wasgeht::Application.config.application_url)

  root  :to => "city_select#index"

  get '/robots.txt'  => 'robots#index', defaults: { format: :text }

  #devise facebook logout
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy', as: :sign_out
  end

  scope '/:area' do
    get '/' => "events#index", :as => :events
    get '/' => "events#index", :as => :area
    get 'e/:uuid' => "events#show", constraints: { uuid: /[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12}/ }, :as => :event
    get 'a/:uuid' => "events#show", constraints: { uuid: /[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12}/ },   defaults: { format: :amp }, :as => :event_amp
    get 'i/:uuid' => "events#show", constraints: { uuid: /[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12}/ },   defaults: { format: :ics }, :as => :event_ics
    get '/was-geht-demnaechst-ab' => "future_events#index", :as => :future_events
    get '/d/was-geht-am-:date-ab' => "future_events#show", :as => :future_event, constraints: { date: /\d(\d)?\.\d(\d)?\.\d\d\d\d/ }
    get '/ueber-uns'    => 'legal#about', :as => :about
    get '/impressum'    => 'legal#imprint', :as => :imprint
    get '/datenschutz'  => 'legal#privacy', :as => :privacy
    get '/agb'          => 'legal#tos', :as => :tos

    scope module: 'sitemap' do
      get '/sitemap.xml'    => 'city#index',  defaults: { format: :xml }, as: :sitemap_city_index
      get '/sitemap/root.xml'    => 'city#root',   defaults: { format: :xml }, as: :sitemap_city_root
      get '/sitemap/:page.xml'    => 'city#show',   defaults: { format: :xml }, constraints: { :page => /\d*+/ }, as: :sitemap_city_show
    end

    scope '/kontakt' do
      get  '/' => 'legal#imprint', :as => :contact_index
    end

    scope '/flyer-hochladen' do
      get  '/' => "upload#index", :as => :upload_index
      post '/' => "upload#create"
      post '/e' => "upload#create_event", as: :upload_index_event
      get  '/finish' => "upload#finish", :as => :finish_upload_index
    end
  end

  get '*unmatched_route', to: 'application#route_not_found'
end

app/controllers/legal_controller.rb
class LegalController < ApplicationController
  force_ssl if Rails.env.production?
  before_action :cache_control

  def index
    respond_to do |format|
      format.html { render(:about) }
    end
  end

  def imprint
    respond_to :html
  end

  def privacy
    respond_to :html
  end

  def tos
    respond_to :html
  end

  def about
    respond_to :html
  end
end

app/views/legal/about.html.erb
<% content_for :title do %>
<%= t(:about_title, :scope => 'helpers.legal', :area => @current_area.name) %>
<% end %>

<% content_for :description do %>
<%= t(:imprint_meta_description, :scope => 'helpers.legal', :area => @current_area.name, extension: 'de') %>
<% end %>

<div class="offset"></div>
<div class="light-wrapper page-title">
  <div class="container inner">
    <h1><%= "Über www.wasgehtheuteab.de" %></h1>
    <div class="collapse navbar-collapse pull-right">
    </div>
  </div>
</div>

<div class="dark-wrapper">
  <div class="container inner">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <p>Seit Oktober 2009 sammeln wir Flyer zu Partys, Ausstellungen, Vernissagen, Festivals, Lesungen und ähnlichem</p>
        <p>Einfach solls sein, für die Spontanen, die morgens noch nicht wissen wo was gegen Abend los ist. Der wichtigste Tag zum feiern, prominent auf der Titelseite: Heute – jeden Tag aufs Neue. </p>
        <p>Der Plattenladen als Sammelstelle für Flyer ist schon vor Jahren abgelöst worden. Wir leben in der Zukunft und wollen ein altes Relikt mitnehmen. Deswegen gibts bei uns alle Flyer übersichtlich auf einer Seite – kein mühsames Suchen mehr in dunklen Bars, Cafes oder sonstigen Plätzen. </p>
        <p>Glücklicherweise gibt es mehr als einen Weg zu erfahren, wohin man Abends weggehen kann. Es sollte für jeden was dabei sein und für ganz Kurzentschloßene funktioniert das ganze natürlich auch auf allen gängigen Smartphones. Einfach ausprobieren. </p> <ul>
        <li><%= link_to "Webseite: www.wasgehtheuteab.de", "https://www.wasgehtheuteab.de" %></li>
        <li><%= link_to "Kurz-URL: www.wgha.de", "https://www.wgha.de" %></li>
        <li><%= link_to 'Mobile Webseite', "https://www.wasgehtheuteab.de" %></li>
      </ul>
      <h5>Events werden von jedermann eingestellt</h5>
      <p>Events können ohne weitere Kosten einfach über <%= link_to 'diesen Link', upload_index_url %> eingestellt werden. </p>
      <p>Ihr erstellt dafür einen Event auf Facebook und kopiert den Link zum Event. Auf der <%= link_to 'Upload-Seite von wgha.de', upload_index_url %> kannst du den Link zum Event auf Facebook in das Feld einfügen, absenden und fertig.</p>
      <p>Stellt eure Flyer am besten so früh wie möglich ein. So ist euer Flyer nicht nur für Besucher der Seite früher zu entdecken, sondern auch für Suchmaschinen. </p>
      <p>Wichtig ist, die Location auf Facebook richtig anzulegen. Wie das geht erfährst du auf der Facebook Hilfe Seite <%= link_to "https://www.facebook.com/help/175921872462772", "https://www.facebook.com/help/175921872462772" %>.</p>
      <p>Uhrzeit und Datum des Events richtig angeben. Versteht sich von selber, oder? </p>
      <p>Beachte bitte <%= link_to "unsere AGB's", tos_url %></p>

      <h5>… und zum Schluss!</h5>
      <p>Wir wünschen euch viel Spass bei finden von tollen Veranstaltungen und beim weggehen. Falls euch die Seite gefällt lasst es und wissen und schreibt uns über <%= link_to 'das Kontaktformular', contact_index_url %> – wir freuen uns immer über Post! </p>
      <!-- /.span9 -->
    </div>
    <!-- /.row -->
  </div>
</div>
</div>

app/views/legal/imprint.html.erb
<% content_for :title do %>
<%= t(:imprint_title, :scope => 'helpers.legal', :area => @current_area.name) %>

<% end %>

<% content_for :description do %>
<%= t(:imprint_meta_description, :scope => 'helpers.legal', :area => @current_area.name, extension: 'de') %>
<% end %>

<div class="offset"></div>
<div class="light-wrapper page-title">
  <div class="container inner">
    <h1>Impressum</h1>
    <div class="collapse navbar-collapse pull-right">
    </div>
  </div>
</div>

<div class="dark-wrapper">
  <div class="container inner">
    <div class="row">
      <aside class="col-sm-5">
        <div class="sidebox widget">
          <address>
            <strong>NAME</strong><br>
            STRASSE<br>
            POSTLEITZAHL ORT<br>
            <abbr title="Phone">Telefon:</abbr> TELEFONNUMMER<br>
            <abbr title="Email">E-Mail:</abbr> <a href="mailto:info@wasgehtheuteab.de">info@wasgehtheuteab.de</a>
          </address>
          <h3>Löschungsanträge</h3>
          <p>Löschanträge für Events bitte per E‑Mail senden und den entsprechenden Event-Link auf wasgehtheuteab.de, sowie einen Grund für die Löschung angeben.</p>
        </div>
        <!-- /.widget -->
      </aside>
      <!-- /.span4 -->
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
</div>
<!-- /.dark-wrapper -->

app/views/legal/privacy.html.erb
<% content_for :title do %>
<%= t(:privacy_title, :scope => 'helpers.legal', :area => @current_area.name) %>
<% end %>

<% content_for :description do %>
<%= t(:imprint_meta_description, :scope => 'helpers.legal', :area => @current_area.name, extension: 'de') %>
<% end %>

<div class="offset"></div>
<div class="light-wrapper page-title">
  <div class="container inner">
    <h1>Datenschutzerkl&auml;rung</h1>
    <div class="collapse navbar-collapse pull-right">
    </div>
  </div>
</div>

<div class="dark-wrapper">
  <div class="container inner">

    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
       <p>wasgehtheuteab nimmt den Schutz Ihrer persönlichen Daten sehr ernst und hält sich strikt an die Regeln der Datenschutzgesetze. Personenbezogene Daten werden auf dieser Webseite nur im technisch notwendigen Umfang erhoben. In keinem Fall werden die erhobenen Daten verkauft oder aus anderen Gründen an Dritte weitergegeben.</p> <p>Die nachfolgende Erklärung gibt Ihnen einen Überblick darüber, wie wir diesen Schutz gewährleisten und welche Art von Daten zu welchem Zweck erhoben werden.</p>

       <h5>Datenverarbeitung auf dieser Internetseite</h5>
       <p>wasgehtheuteab erhebt und speichert automatisch in sog. Server Log Files Informationen, die Ihr Browser an uns übermittelt. Dies sind unter anderem: </p> <ul> <li>Browsertyp/ -version</li> <li>verwendetes Betriebssystem</li> <li>Referrer URL (die zuvor besuchte Seite)</li> <li>Hostname des zugreifenden Rechners (IP Adresse)</li> <li>Uhrzeit der Serveranfrage.</li> </ul> <p>Diese Daten sind für wasgehtheuteab nicht bestimmten Personen zuordenbar. Eine Zusammenführung dieser Daten mit anderen Datenquellen wird nicht vorgenommen. </p> <h5>Kontaktaufnahme</h5> <p>Bei der Kontaktaufnahme mit dem Anbieter (zum Beispiel per Kontaktformular oder E-Mail) werden die Angaben des Nutzers zwecks Bearbeitung der Anfrage sowie für den Fall, dass Anschlussfragen entstehen, gespeichert.</p>

       <h5>Datenschutzerklärung für die Nutzung von Facebook-Plugins (Login-Button)</h5>
       <p>Auf unseren Seiten sind Plugins des sozialen Netzwerks Facebook, 1601 South California Avenue, Palo Alto, CA 94304, USA integriert. Die Facebook-Plugins erkennen Sie an dem Facebook-Logo oder dem "Login-Button" auf unserer Seite. Eine Übersicht über die Facebook-Plugins finden Sie hier: <a href="http://developers.facebook.com/docs/plugins/">http://developers.facebook.com/docs/plugins/</a> </p> <p>Wenn Sie unsere Upload-Seiten besuchen, wird über das Plugin eine direkte Verbindung zwischen Ihrem Browser und dem Facebook-Server hergestellt. Facebook erhält dadurch die Information, dass Sie mit Ihrer IP-Adresse unsere Seite besucht haben. Wenn Sie den Facebook "Anmelden-Button" anklicken, können Sie Events von Facebook auf unserer Seite hinterlegen. Dadurch kann Facebook den Besuch unserer Seiten Ihrem Benutzerkonto zuordnen. Wir weisen darauf hin, dass wir als Anbieter der Seiten keine Kenntnis vom Inhalt der übermittelten Daten sowie deren Nutzung durch Facebook erhalten. Weitere Informationen hierzu finden Sie in der Datenschutzerklärung von facebook unter <a href="http://de-de.facebook.com/policy.php">http://de-de.facebook.com/policy.php</a> </p> <p>Wenn Sie nicht wünschen, dass Facebook den Besuch unserer Seiten Ihrem Facebook-Nutzerkonto zuordnen kann, loggen Sie sich bitte aus Ihrem Facebook-Benutzerkonto aus.</p>
       <!-- /.span9 -->

       <h5>Datenschutzerklärung für Google AdSense</h5>
       <p>Unsere Website benutzt Google AdSense, einen Dienst zum Einbinden von Werbeanzeigen von Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA. Google AdSense verwendet sog. "Cookies", Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website ermöglicht. Google AdSense verwendet auch so genannte Web Beacons (unsichtbare Grafiken). Durch diese Web Beacons können Informationen wie der Besucherverkehr auf diesen Seiten ausgewertet werden. Die durch Cookies und Web Beacons erzeugten Informationen über die Benutzung dieser Website (einschließlich Ihrer IP-Adresse) und Auslieferung von Werbeformaten werden an einen Server von Google in den USA übertragen und dort gespeichert. Diese Informationen können von Google an Vertragspartner von Google weiter gegeben werden. Google wird Ihre IP-Adresse jedoch nicht mit anderen von Ihnen gespeicherten Daten zusammenführen. Sie können die Installation der Cookies durch eine entsprechende Einstellung Ihrer Browser Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website voll umfänglich nutzen können. Durch die Nutzung dieser Website erklären Sie sich mit der Bearbeitung der über Sie erhobenen Daten durch Google in der zuvor beschriebenen Art und Weise und zu dem zuvor benannten Zweck einverstanden.</p>
     </div>
     <!-- /.row -->
   </div>
 </div>
</div>

app/views/legal/tos.html.erb
<% content_for :title do %>
<%= t(:tos_title, :scope => 'helpers.legal', :area => @current_area.name) %>
<% end %>

<% content_for :description do %>
<%= t(:imprint_meta_description, :scope => 'helpers.legal', :area => @current_area.name, extension: 'de') %>
<% end %>

<div class="offset"></div>
<div class="light-wrapper page-title">
  <div class="container inner">
    <h1>Allgemeine Gesch&auml;ftsbedingungen</h1>
    <div class="collapse navbar-collapse pull-right"></div>
  </div>
</div>

<div class="dark-wrapper">
  <div class="container inner">
    <div class="section-title text-center">
    </div>

    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <h5>1. Anspruch</h5>
        <p>Auf den kostenlosen Service kann keiner Anspruch erheben und der Betreiber kann jederzeit User hiervon ausschließen. Sollte das Onlineangebot einmal nicht zu erreichen sein, übernimmt der Betreiber keinerlei Haftung. </p>

        <h5>2. Verbotener Inhalt</h5>
        <p>Der User ist für seine publizierten Inhalte selbst verantwortlich. Er versichert, über den Service keine Inhalte zu verbreiten, die gegen geltendes Recht oder Vereinbarungen mit Dritten verstoßen, insbesondere keine beleidigenden, obszönen, rassistischen, bedrohenden, belästigenden, diffamierenden und sexuell ausgerichteten Inhalte zu verbreiten. </p>
        <p>Der Benutzer versichert ausdrücklich, dass die Bereitstellung und Veröffentlichung der Inhalte weder gegen Deutsches Recht, insbesondere Urheber-, Datenschutz- und Wettbewerbsrecht, verstößt. Der Betreiber behält sich vor, sämtliche Daten aus jeglichem Grund auch ohne Erläuterungen von einer Speicherung auf dem Server auszunehmen. Es besteht für den Betreiber keine Prüfungspflicht auf die Rechtmäßigkeit der Daten. </p>

        <h5>3. Datenschutz</h5>
        <p>Alle Angaben von persönlichen Daten sind freiwillig und werden vertraulich behandelt. Persönlich Daten werden nicht an dritte weitergegeben. </p>

        <h5>4. Kontrolle durch den Betreiber</h5>
        <p>Der User erklärt sich damit einverstanden, dass alle von ihm hochgeladenen Dateien auf verbotenen Inhalt (siehe 2.) kontrolliert werden. </p>

        <h5>5. Einsatz von Programmen</h5>
        <p>Der User verpflichtet sich keine Programme oder Bots zu benutzen, die den Service in irgendeiner Weise beeinflussen. </p>

        <h5>6. Änderungen</h5>
        <p>Der Betreiber hat jederzeit das Recht die AGB zu verändern. Sollte der Benutzer damit nicht einverstanden sein, so wird er zukünftig von dem Onlineangebot ausgeschlossen. </p>

        <h5>7. Rechtswirksamkeit dieses Haftungsausschlusses</h5>
        <p>Dieser Haftungsausschluss ist als Teil des Internetangebotes zu betrachten, von dem aus auf diese Seite verwiesen wurde. Sofern Teile oder einzelne Formulierungen dieses Textes der geltenden Rechtslage nicht, nicht mehr oder nicht vollständig entsprechen sollten, bleiben die übrigen Teile des Dokumentes in ihrem Inhalt und ihrer Gültigkeit davon unberührt. </p>

        <h2>Disclaimer</h2>
        <h5>1. Inhalt des Onlineangebotes</h5>
        <p>Der Autor übernimmt keinerlei Gewähr für die Aktualität, Korrektheit, Vollständigkeit oder Qualität der bereitgestellten Informationen. Haftungsansprüche gegen den Autor, welche sich auf Schäden materieller oder ideeller Art beziehen, die durch die Nutzung oder Nichtnutzung der dargebotenen Informationen bzw. durch die Nutzung fehlerhafter und unvollständiger Informationen verursacht wurden, sind grundsätzlich ausgeschlossen, sofern seitens des Autors kein nachweislich vorsätzliches oder grob fahrlässiges Verschulden vorliegt. </p>
        <p>Alle Angebote sind freibleibend und unverbindlich. Der Autor behält es sich ausdrücklich vor, Teile der Seiten oder das gesamte Angebot ohne gesonderte Ankündigung zu verändern, zu ergänzen, zu löschen oder die Veröffentlichung zeitweise oder endgültig einzustellen. </p>

        <h5>2. Verweise und Links</h5>
        <p>Bei direkten oder indirekten Verweisen auf fremde Webseiten ("Hyperlinks"), die außerhalb des Verantwortungsbereiches des Autors liegen, würde eine Haftungsverpflichtung ausschließlich in dem Fall in Kraft treten, in dem der Autor von den Inhalten Kenntnis hat und es ihm technisch möglich und zumutbar wäre, die Nutzung im Falle rechtswidriger Inhalte zu verhindern. </p>

        <p>Der Autor erklärt hiermit ausdrücklich, dass zum Zeitpunkt der Linksetzung keine illegalen Inhalte auf den zu verlinkenden Seiten erkennbar waren. Auf die aktuelle und zukünftige Gestaltung, die Inhalte oder die Urheberschaft der gelinkten/verknüpften Seiten hat der Autor keinerlei Einfluss. Deshalb distanziert er sich hiermit ausdrücklich von allen Inhalten aller gelinkten /verknüpften Seiten, die nach der Linksetzung verändert wurden. Diese Feststellung gilt für alle innerhalb des eigenen Internet-angebotes gesetzten Links und Verweise sowie für Fremdeinträge in vom Autor eingerichteten Gästebüchern, Diskussionsforen, Linkverzeichnissen, Mailinglisten und in allen anderen Formen von Datenbanken, auf deren Inhalt externe Schreibzugriffe möglich sind. Für illegale, fehlerhafte oder unvollständige Inhalte und insbesondere für Schäden, die aus der Nutzung oder Nichtnutzung solcherart dargebotener Informationen entstehen, haftet allein der Anbieter der Seite, auf welche verwiesen wurde, nicht derjenige, der über Links auf die jeweilige Veröffentlichung lediglich verweist. </p>

        <h5>3. Urheber- und Kennzeichenrecht</h5>
        <p>Der Autor ist bestrebt, in allen Publikationen die Urheberrechte der verwendeten Grafiken, Tondokumente, Videosequenzen und Texte zu beachten, von ihm selbst erstellte Grafiken, Tondokumente, Videosequenzen und Texte zu nutzen oder auf lizenzfreie Grafiken, Tondokumente, Videosequenzen und Texte zurückzugreifen. </p>

        <p>Alle innerhalb des Internetangebotes genannten und ggf. durch Dritte geschützten Marken- und Warenzeichen unterliegen uneingeschränkt den Bestimmungen des jeweils gültigen Kennzeichenrechts und den Besitzrechten der jeweiligen eingetragenen Eigentümer. Allein aufgrund der bloßen Nennung ist nicht der Schluss zu ziehen, dass Markenzeichen nicht durch Rechte Dritter geschützt sind! </p>

        <p>Das Copyright für veröffentlichte, vom Autor selbst erstellte Objekte bleibt allein beim Autor der Seiten. Eine Vervielfältigung oder Verwendung solcher Grafiken, Tondokumente, Videosequenzen und Texte in anderen elektronischen oder gedruckten Publikationen ist ohne ausdrückliche Zustimmung des Autors nicht gestattet. </p>

        <h5>4. Datenschutz</h5>
        <p>Sofern innerhalb des Internetangebotes die Möglichkeit zur Eingabe persönlicher oder geschäftlicher Daten (E-Mail-Adressen, Namen, Anschriften) besteht, so erfolgt die Preisgabe dieser Daten seitens des Nutzers auf ausdrücklich freiwilliger Basis. Die Inanspruchnahme und Bezahlung aller angebotenen Dienste ist - soweit technisch möglich und zumutbar - auch ohne Angabe solcher Daten bzw. unter Angabe anonymisierter Daten oder eines Pseudonyms gestattet. Die Nutzung der im Rahmen des Impressums oder vergleichbarer Angaben veröffentlichten Kontaktdaten wie Postanschriften, Telefon- und Faxnummern sowie E-Mail-Adressen durch Dritte zur Übersendung von nicht ausdrücklich angeforderten Informationen ist nicht gestattet. Rechtliche Schritte gegen die Versender von sogenannten Spam-Mails bei Verstössen gegen dieses Verbot sind ausdrücklich vorbehalten. </p>

        <h5>5. Rechtswirksamkeit dieses Haftungsausschlusses</h5>
        <p>Dieser Haftungsausschluss ist als Teil des Internetangebotes zu betrachten, von dem aus auf diese Seite verwiesen wurde. Sofern Teile oder einzelne Formulierungen dieses Textes der geltenden Rechtslage nicht, nicht mehr oder nicht vollständig entsprechen sollten, bleiben die übrigen Teile des Dokumentes in ihrem Inhalt und ihrer Gültigkeit davon unberührt. </p>
        <!-- /.span9 -->
      </div>
      <!-- /.row -->
    </div>
  </div>
</div>