config/routes.rb
Rails.application.routes.draw do
  #devise facebook login
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get '/favicon.bmp' => redirect(path: "/assets/favicon.ico", host: Wasgeht::Application.config.application_url)
  get '/apple-touch-icon-*png' => redirect(path: '/assets/apple-touch-icon.png', host: Wasgeht::Application.config.application_url)

  root  :to => "city_select#index"

  get '/robots.txt'  => 'robots#index', defaults: { format: :text }

  #devise facebook logout
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy', as: :sign_out
  end

  scope '/:area' do
    get '/' => "events#index", :as => :events
    get '/' => "events#index", :as => :area
    get 'e/:uuid' => "events#show", constraints: { uuid: /[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12}/ }, :as => :event
    get 'a/:uuid' => "events#show", constraints: { uuid: /[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12}/ },   defaults: { format: :amp }, :as => :event_amp
    get 'i/:uuid' => "events#show", constraints: { uuid: /[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12}/ },   defaults: { format: :ics }, :as => :event_ics
    get '/was-geht-demnaechst-ab' => "future_events#index", :as => :future_events
    get '/d/was-geht-am-:date-ab' => "future_events#show", :as => :future_event, constraints: { date: /\d(\d)?\.\d(\d)?\.\d\d\d\d/ }
    get '/ueber-uns'    => 'legal#about', :as => :about
    get '/impressum'    => 'legal#imprint', :as => :imprint
    get '/datenschutz'  => 'legal#privacy', :as => :privacy
    get '/agb'          => 'legal#tos', :as => :tos

    scope module: 'sitemap' do
      get '/sitemap.xml'    => 'city#index',  defaults: { format: :xml }, as: :sitemap_city_index
      get '/sitemap/root.xml'    => 'city#root',   defaults: { format: :xml }, as: :sitemap_city_root
      get '/sitemap/:page.xml'    => 'city#show',   defaults: { format: :xml }, constraints: { :page => /\d*+/ }, as: :sitemap_city_show
    end

    scope '/kontakt' do
      get  '/' => 'legal#imprint', :as => :contact_index
    end

    scope '/flyer-hochladen' do
      get  '/' => "upload#index", :as => :upload_index
      post '/' => "upload#create"
      post '/e' => "upload#create_event", as: :upload_index_event
      get  '/finish' => "upload#finish", :as => :finish_upload_index
    end
  end

  get '*unmatched_route', to: 'application#route_not_found'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= yield :title %></title>
  <link rel="shortcut icon" href="<%= image_path 'favicon.png' %>">
  <meta name='description' content='<%= yield :description %>' >

  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <%= javascript_include_tag 'html5shiv.js' %>
  <%= javascript_include_tag '//oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js' %>
  <![endif]-->

  <meta content='de_DE' property='og:locale'>
  <%= yield :facebook_property %>
  <%= yield :meta_refresh %>

  <link href='<%= image_path 'favicon.ico' %>' rel='shortcut icon' type='image/x-icon'>
  <link href='<%= image_path 'favicon.ico' %>' rel='icon' type='image/vnd.microsoft.icon'>

  <%= yield :hreflang %>

  <link rel="apple-touch-icon" href="<%= image_path 'apple-touch-icon.png' %>" />
  <link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'apple-touch-icon-57x57.png' %>" />
  <link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'apple-touch-icon-72x72.png' %>" />
  <link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'apple-touch-icon-114x114.png' %>" />
  <link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'apple-touch-icon-144x144.png' %>" />
  <link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'apple-touch-icon-60x60.png' %>" />
  <link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'apple-touch-icon-120x120.png' %>" />
  <link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'apple-touch-icon-76x76.png' %>" />
  <link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'apple-touch-icon-152x152.png' %>" />

  <meta name="apple-mobile-web-app-title" content="Was geht heute ab">
  <meta name="application-name" content="Was geht heute ab">

  <link rel="alternate" type="application/rss+xml" title="<%= "Was geht heute ab in #{@current_area.name}?" %>" href="<%= area_url(format: 'rss') %>">
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-2540422383235659",
            enable_page_level_ads: true
       });
  </script>
</head>

<body class="full-layout">
  <div class="body-wrapper">
    <div class="yamm navbar basic default">
      <div class="navbar-header">
        <div class="container">
          <div class="basic-wrapper"> <a class="btn responsive-menu pull-right" data-toggle="collapse" data-target=".navbar-collapse"><i class='icon-menu-1'></i></a> <a class="navbar-brand" href="<%= area_path %>"><img src="<%= image_path 'logo.png' %>" alt="logo" /></a> </div>

          <div class="collapse navbar-collapse pull-left">
            <ul class="nav navbar-nav">
              <li><a href="<%= area_url %>">Was geht heute ab? <%= @current_area.name %></a>
              </li>
            </ul>
            <div class="collapse navbar-collapse pull-right">
              <ul class="nav navbar-nav">
                <li><a href="<%= area_url %>">Heute</a>
                </li>
                <li><a href="<%= future_events_url %>">Demn&auml;chst</a>
                </li>
                <li><a href="<%= upload_index_url %>">Party eintragen</a>
                </li>
                <li><a href="<%= root_url(area: nil) %>">Stadt wechseln</a>
                </li>
                <% if current_user %>
                  <li>
                    <%= link_to '<img src="/fb_button/logout.png" style="max-width: 300px; margin-top: -25px" />'.html_safe, sign_out_url, :method => :delete %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <!--/.nav-collapse -->
      </div>
    </div>
    <!--/.navbar -->

    <%= yield %>

    <footer class="black-wrapper">
      <div class="sub-footer">
        <div class="container">
          <p class="pull-left"><%= link_to "#{request.subdomain}.wasgehtheuteab.de", root_url(area: nil) %></p>
          <ul class="footer-menu pull-right">
            <li><%= link_to "Über wasgehtheuteab.de", about_url %></li>
            <li><%= link_to 'RSS', area_url(format: 'rss') %></li>
            <li><%= link_to 'Kontakt', imprint_url %></li>
            <li><%= link_to 'Impressum', imprint_url %></li>
            <li><%= link_to 'Datenschutz', privacy_url %></li>
            <li><%= link_to 'AGB', tos_url %></li>
          </ul>
        </div>
      </div>
    </footer>
    <!-- /footer -->
  </div>
  <!-- /.body-wrapper -->

  <script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "WebSite",
    "name": "Was geht heute ab?",
    "alternateName": "wgha",
    "url": "<%= root_url(area: nil) %>"
  }
  </script>
  <script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "Organization",
    "url": "<%= root_url(area: nil) %>",
    "logo": "<%= image_url 'logo.png' %>"
  }
  </script>
</body>
</html>

app/views/layouts/city_select.html.erb
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="utf-8">
  <title><%= yield :title %></title>
  <meta name='description' content='<%= yield :description %>' >
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag 'trimmed' %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <%= javascript_include_tag 'html5shiv.js', async: Rails.env.production? %>
  <%= javascript_include_tag 'https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js', async: Rails.env.production? %>
  <![endif]-->

  <link rel="shortcut icon" href="<%= image_path 'favicon.ico' %>">
  <link href='<%= image_path 'favicon.ico' %>' rel='shortcut icon' type='image/x-icon'>
  <link href='<%= image_path 'favicon.ico' %>' rel='icon' type='image/vnd.microsoft.icon'>

  <link rel="apple-touch-icon" href="<%= image_path 'apple-touch-icon.png' %>" />
  <link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'apple-touch-icon-57x57.png' %>" />
  <link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'apple-touch-icon-72x72.png' %>" />
  <link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'apple-touch-icon-114x114.png' %>" />
  <link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'apple-touch-icon-144x144.png' %>" />
  <link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'apple-touch-icon-60x60.png' %>" />
  <link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'apple-touch-icon-120x120.png' %>" />
  <link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'apple-touch-icon-76x76.png' %>" />
  <link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'apple-touch-icon-152x152.png' %>" />
  <%= yield :hreflang %>
</head>

<body class="full-layout">
  <div class="body-wrapper">

    <%= yield %>

    <footer class="black-wrapper">
      <div class="sub-footer">
        <div class="container">
          <p class="pull-left"><%= link_to "#{request.subdomain}.wasgehtheuteab.de", root_url(area: nil) %></p>
          <ul class="footer-menu pull-right">
            <li><%= link_to 'Kontakt', imprint_url(area: Area.first.domain) %></li>
            <li><%= link_to 'Impressum', imprint_url(area: Area.first.domain) %></li>
            <li><%= link_to 'Datenschutz', privacy_url(area: Area.first.domain) %></li>
            <li><%= link_to 'AGB', tos_url(area: Area.first.domain) %></li>
          </ul>
        </div>
      </div>
    </footer>
    <!-- /footer -->
  </div>
  <!-- /.body-wrapper -->

  <script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "WebSite",
    "name": "Was geht heute ab?",
    "alternateName": "wgha",
    "url": "<%= root_url(area: nil) %>"
  }
  </script>
  <script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "Organization",
    "url": "<%= root_url(area: nil) %>",
    "logo": "<%= image_url 'logo.png' %>"
  }
  </script>
  <script type="application/ld+json">
  {
    "@context":"http://schema.org",
    "@type":"BreadcrumbList",
    "itemListElement":[
    {"item":{"@id":"<%= root_url(area: nil) %>","name":"<%= "Alle Städte" %> "},"@type":"ListItem","position":1}]}
</script>
</body>
</html>